version: '3.8'

services:
  nextjs-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEO4J_URI=neo4j://localhost:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=strongpassword
    depends_on:
      - neo4j-db

  neo4j-db:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/strongpassword
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:
